[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "cd web-app/backend && gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT app:app"